controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST
api_login_check:
  path: /api/login_check
  controller: App\Controller\AuthController::getTokenUser

